return {
{
title = "RC Standard",
id = 'RCMetadataSetOne',
items = {
{ "com.adobe.label", label = "File Info" },
'com.adobe.filename',
'com.adobe.originalFilename.ifDiffers',
'com.adobe.sidecars',
'com.adobe.copyname',
'com.adobe.folder',
'com.adobe.filesize',
'com.adobe.filetype',
'com.adobe.fileFormat',
'com.adobe.dateTime.onlyIfUnique',
'com.adobe.dateTimeOriginal',
'com.adobe.dateTimeDigitized.onlyIfUnique',
'com.adobe.colorLabels',
'com.adobe.metadataStatus',
'com.adobe.metadataDate',
'com.adobe.audioAnnotation',
'com.adobe.imageFileDimensions',
'com.adobe.imageCroppedDimensions',
'com.adobe.separator',
{ "com.adobe.label", label = "Title & Caption" },
'com.adobe.title',
{ 'com.adobe.caption', height_in_lines = 3 },
'com.adobe.separator',
{ "com.adobe.label", label = "Shooting Info" },
'com.adobe.shutterSpeedValue',
'com.adobe.apertureValue',
'com.adobe.brightnessValue',
'com.adobe.exposureBiasValue',
'com.adobe.flash',
'com.adobe.exposureProgram',
'com.adobe.meteringMode',
'com.adobe.ISOSpeedRating',
'com.adobe.focalLength',
'com.adobe.focalLength35mm',
'com.adobe.lens',
'com.adobe.subjectDistance',
'com.adobe.make',
'com.adobe.model',
'com.adobe.serialNumber',
'com.adobe.artist',
'com.adobe.software',
'com.adobe.separator',
{ "com.adobe.label", label = "Creator" },
'com.adobe.creator',
'com.adobe.creatorJobTitle',
'com.adobe.creatorWorkWebsite',
'com.adobe.separator',
{ "com.adobe.label", label = "Genre, Scene, & Location" },
'com.adobe.intellectualGenre',
'com.adobe.scene',
'com.adobe.location',
'com.adobe.city',
'com.adobe.state',
'com.adobe.country',
'com.adobe.isoCountryCode',
'com.robcole.lightroom.CustomMetadata.*',
'com.robcole.dev.ChangeManager.*',
'com.robcole.lightroom.ChangeManager.*',
'com.robcole.lightroom.metadata.RC_CustomMetadata.*',
'com.robcole.lightroom.develop.DevAdjust.*',
'com.adobe.separator',
{ "com.adobe.label", label = "RC Dev Meta" },
'com.adobe.separator',
'com.robcole.DevMeta.lastUpdate',
'com.adobe.separator',
'com.robcole.DevMeta.ProcessVersion',
'com.adobe.separator',
{ "com.adobe.label", label = "Camera Calibration" },
'com.robcole.DevMeta.CameraProfile',
'com.robcole.DevMeta.ShadowTint',
'com.robcole.DevMeta.rgbColorMods',
'com.adobe.separator',
{ "com.adobe.label", label = "Basic" },
'com.robcole.DevMeta.WhiteBalance',
'com.robcole.DevMeta.Temperature',
'com.robcole.DevMeta.Tint',
'com.adobe.separator',
'com.robcole.DevMeta.Exposure2012',
'com.robcole.DevMeta.Contrast2012',
'com.robcole.DevMeta.Highlights2012',
'com.robcole.DevMeta.Shadows2012',
'com.robcole.DevMeta.Whites2012',
'com.robcole.DevMeta.Blacks2012',
'com.robcole.DevMeta.Clarity2012',
'com.adobe.separator',
'com.robcole.DevMeta.Vibrance',
'com.robcole.DevMeta.Saturation',
'com.adobe.separator',
'com.robcole.DevMeta.Exposure',
'com.robcole.DevMeta.HighlightRecovery',
'com.robcole.DevMeta.FillLight',
'com.robcole.DevMeta.Shadows',
'com.robcole.DevMeta.Brightness',
'com.robcole.DevMeta.Contrast',
'com.robcole.DevMeta.Clarity',
'com.adobe.separator',
{ "com.adobe.label", label = "Tone Curve" },
'com.robcole.DevMeta.ToneCurveName',
'com.robcole.DevMeta.toneCurveParamMods',
'com.robcole.DevMeta.toneCurvePointMods',
'com.robcole.DevMeta.channelCurveMods',
'com.adobe.separator',
{ "com.adobe.label", label = "HSL / Color / B & W" },
'com.robcole.DevMeta.colorType',
'com.robcole.DevMeta.colorMods',
'com.adobe.separator',
{ "com.adobe.label", label = "Split Toning" },
'com.robcole.DevMeta.splitToning',
'com.adobe.separator',
{ "com.adobe.label", label = "Detail" },
'com.robcole.DevMeta.Sharpness',
'com.robcole.DevMeta.SharpenRadius',
'com.robcole.DevMeta.SharpenDetail',
'com.robcole.DevMeta.SharpenEdgeMasking',
'com.adobe.separator',
'com.robcole.DevMeta.LuminanceSmoothing',
'com.robcole.DevMeta.LuminanceNoiseReductionDetail',
'com.robcole.DevMeta.LuminanceNoiseReductionContrast',
'com.adobe.separator',
'com.robcole.DevMeta.ColorNoiseReduction',
'com.robcole.DevMeta.ColorNoiseReductionDetail',
'com.adobe.separator',
{ "com.adobe.label", label = "Lens Corrections" },
'com.robcole.DevMeta.lensDistortion',
'com.robcole.DevMeta.lensVignetting',
'com.robcole.DevMeta.lensCa',
'com.robcole.DevMeta.perspective',
'com.adobe.separator',
{ "com.adobe.label", label = "Effects" },
'com.robcole.DevMeta.postCropVignette',
'com.robcole.DevMeta.grain',
'com.adobe.separator',
{ "com.adobe.label", label = "Crop, Locals, & Retouch" },
'com.robcole.DevMeta.CropWidth',
'com.robcole.DevMeta.CropHeight',
'com.robcole.DevMeta.retouched',
'com.robcole.DevMeta.redeye',
'com.robcole.DevMeta.gradients',
'com.robcole.DevMeta.brushes',
'com.adobe.separator',
'com.robcole.DevMeta.stackPos',
'com.robcole.DevMeta.pixelCount',
'com.robcole.DevMeta.aspectRatio',
'com.robcole.lightroom.NxToo.*',
'com.robcole.lightroom.plugin.nxTooey3.*',
'com.adobe.separator',
{"com.adobe.label", label="RC Exif Meta" },
'com.adobe.separator',
'com.robcole.lightroom.ExifMeta.lastUpdate',
'com.adobe.separator',
{ 'com.adobe.label', label = 'Canon' },
'com.robcole.lightroom.ExifMeta.Canon_AFAreaMode',
'com.robcole.lightroom.ExifMeta.Canon_AFPoint',
'com.robcole.lightroom.ExifMeta.Canon_AFPointsInFocus',
'com.robcole.lightroom.ExifMeta.Canon_AFPointsSelected',
'com.robcole.lightroom.ExifMeta.Canon_FlashExposureComp',
'com.robcole.lightroom.ExifMeta.Canon_FocusDistanceLower',
'com.robcole.lightroom.ExifMeta.Canon_FocusDistanceUpper',
'com.robcole.lightroom.ExifMeta.Canon_FocusMode',
'com.robcole.lightroom.ExifMeta.Canon_FocusRange',
'com.robcole.lightroom.ExifMeta.Canon_ImageStabilization',
'com.robcole.lightroom.ExifMeta.Canon_MeteringMode',
'com.robcole.lightroom.ExifMeta.Canon_PictureStyle',
{ 'com.adobe.label', label = 'Composite' },
'com.robcole.lightroom.ExifMeta.Composite_CircleOfConfusion',
'com.robcole.lightroom.ExifMeta.Composite_DOF',
'com.robcole.lightroom.ExifMeta.Composite_FOV',
'com.robcole.lightroom.ExifMeta.Composite_FocalLength35efl',
'com.robcole.lightroom.ExifMeta.Composite_HyperfocalDistance',
'com.robcole.lightroom.ExifMeta.Composite_Lens',
'com.robcole.lightroom.ExifMeta.Composite_Lens35efl',
'com.robcole.lightroom.ExifMeta.Composite_LensID',
'com.robcole.lightroom.ExifMeta.Composite_LensSpec',
{ 'com.adobe.label', label = 'ExifIFD' },
'com.robcole.lightroom.ExifMeta.ExifIFD_CreateDate',
'com.robcole.lightroom.ExifMeta.ExifIFD_DateTimeOriginal',
'com.robcole.lightroom.ExifMeta.ExifIFD_ExposureCompensation',
'com.robcole.lightroom.ExifMeta.ExifIFD_ExposureMode',
'com.robcole.lightroom.ExifMeta.ExifIFD_ExposureProgram',
'com.robcole.lightroom.ExifMeta.ExifIFD_Flash',
'com.robcole.lightroom.ExifMeta.ExifIFD_FocalLengthIn35mmFormat',
'com.robcole.lightroom.ExifMeta.ExifIFD_MeteringMode',
'com.robcole.lightroom.ExifMeta.ExifIFD_Saturation',
'com.robcole.lightroom.ExifMeta.ExifIFD_SceneCaptureType',
'com.robcole.lightroom.ExifMeta.ExifIFD_SceneType',
'com.robcole.lightroom.ExifMeta.ExifIFD_SubjectDistance',
'com.robcole.lightroom.ExifMeta.ExifIFD_SubjectDistanceRange',
'com.robcole.lightroom.ExifMeta.ExifIFD_UserComment',
'com.robcole.lightroom.ExifMeta.ExifIFD_WhiteBalance',
{ 'com.adobe.label', label = 'Nikon' },
'com.robcole.lightroom.ExifMeta.Nikon_AFAreaMode',
'com.robcole.lightroom.ExifMeta.Nikon_AFFineTune',
'com.robcole.lightroom.ExifMeta.Nikon_AFPointsUsed',
'com.robcole.lightroom.ExifMeta.Nikon_ActiveDLighting',
'com.robcole.lightroom.ExifMeta.Nikon_AutoDistortionControl',
'com.robcole.lightroom.ExifMeta.Nikon_Brightness',
'com.robcole.lightroom.ExifMeta.Nikon_Contrast',
'com.robcole.lightroom.ExifMeta.Nikon_FilterEffect',
'com.robcole.lightroom.ExifMeta.Nikon_FlashExposureComp',
'com.robcole.lightroom.ExifMeta.Nikon_FocusDistance',
'com.robcole.lightroom.ExifMeta.Nikon_FocusMode',
'com.robcole.lightroom.ExifMeta.Nikon_HueAdjustment',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlAdjust',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlBase',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlName',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlQuickAdjust',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlVersion',
'com.robcole.lightroom.ExifMeta.Nikon_Quality',
'com.robcole.lightroom.ExifMeta.Nikon_Saturation',
'com.robcole.lightroom.ExifMeta.Nikon_Sharpness',
'com.robcole.lightroom.ExifMeta.Nikon_ShootingMode',
'com.robcole.lightroom.ExifMeta.Nikon_VibrationReduction',
{ 'com.adobe.label', label = 'Olympus' },
'com.robcole.lightroom.ExifMeta.Olympus_AFPoint',
'com.robcole.lightroom.ExifMeta.Olympus_FlashExposureComp',
'com.robcole.lightroom.ExifMeta.Olympus_FocusDistance',
'com.robcole.lightroom.ExifMeta.Olympus_FocusMode',
'com.robcole.lightroom.ExifMeta.Olympus_MeteringMode',
'com.robcole.lightroom.ExifMeta.Olympus_PictureMode',
'com.robcole.lightroom.ExifMeta.Olympus_SceneMode',
{ 'com.adobe.label', label = 'XMPaux' },
'com.robcole.lightroom.ExifMeta.XMPaux_ApproximateFocusDistance',
{ 'com.adobe.label', label = 'XMPcrs' },
'com.robcole.lightroom.ExifMeta.XMPcrs_WhiteBalance',
{ 'com.adobe.label', label = 'XMPexif' },
'com.robcole.lightroom.ExifMeta.XMPexif_FocalLengthIn35mmFormat',
},
},
{
title = "RC Custom",
id = 'RCMetadataSetTwo',
items = {
'com.adobe.filename',
'com.adobe.separator',
{"com.adobe.label", label="RC Exif Meta" },
'com.adobe.separator',
'com.robcole.lightroom.ExifMeta.lastUpdate',
'com.adobe.separator',
{ 'com.adobe.label', label = 'Canon' },
'com.robcole.lightroom.ExifMeta.Canon_AFAreaMode',
'com.robcole.lightroom.ExifMeta.Canon_AFPoint',
'com.robcole.lightroom.ExifMeta.Canon_AFPointsInFocus',
'com.robcole.lightroom.ExifMeta.Canon_AFPointsSelected',
'com.robcole.lightroom.ExifMeta.Canon_FlashExposureComp',
'com.robcole.lightroom.ExifMeta.Canon_FocusDistanceLower',
'com.robcole.lightroom.ExifMeta.Canon_FocusDistanceUpper',
'com.robcole.lightroom.ExifMeta.Canon_FocusMode',
'com.robcole.lightroom.ExifMeta.Canon_FocusRange',
'com.robcole.lightroom.ExifMeta.Canon_ImageStabilization',
'com.robcole.lightroom.ExifMeta.Canon_MeteringMode',
'com.robcole.lightroom.ExifMeta.Canon_PictureStyle',
{ 'com.adobe.label', label = 'Composite' },
'com.robcole.lightroom.ExifMeta.Composite_CircleOfConfusion',
'com.robcole.lightroom.ExifMeta.Composite_DOF',
'com.robcole.lightroom.ExifMeta.Composite_FOV',
'com.robcole.lightroom.ExifMeta.Composite_FocalLength35efl',
'com.robcole.lightroom.ExifMeta.Composite_HyperfocalDistance',
'com.robcole.lightroom.ExifMeta.Composite_Lens',
'com.robcole.lightroom.ExifMeta.Composite_Lens35efl',
'com.robcole.lightroom.ExifMeta.Composite_LensID',
'com.robcole.lightroom.ExifMeta.Composite_LensSpec',
{ 'com.adobe.label', label = 'ExifIFD' },
'com.robcole.lightroom.ExifMeta.ExifIFD_CreateDate',
'com.robcole.lightroom.ExifMeta.ExifIFD_DateTimeOriginal',
'com.robcole.lightroom.ExifMeta.ExifIFD_ExposureCompensation',
'com.robcole.lightroom.ExifMeta.ExifIFD_ExposureMode',
'com.robcole.lightroom.ExifMeta.ExifIFD_ExposureProgram',
'com.robcole.lightroom.ExifMeta.ExifIFD_Flash',
'com.robcole.lightroom.ExifMeta.ExifIFD_FocalLengthIn35mmFormat',
'com.robcole.lightroom.ExifMeta.ExifIFD_MeteringMode',
'com.robcole.lightroom.ExifMeta.ExifIFD_Saturation',
'com.robcole.lightroom.ExifMeta.ExifIFD_SceneCaptureType',
'com.robcole.lightroom.ExifMeta.ExifIFD_SceneType',
'com.robcole.lightroom.ExifMeta.ExifIFD_SubjectDistance',
'com.robcole.lightroom.ExifMeta.ExifIFD_SubjectDistanceRange',
'com.robcole.lightroom.ExifMeta.ExifIFD_UserComment',
'com.robcole.lightroom.ExifMeta.ExifIFD_WhiteBalance',
{ 'com.adobe.label', label = 'Nikon' },
'com.robcole.lightroom.ExifMeta.Nikon_AFAreaMode',
'com.robcole.lightroom.ExifMeta.Nikon_AFFineTune',
'com.robcole.lightroom.ExifMeta.Nikon_AFPointsUsed',
'com.robcole.lightroom.ExifMeta.Nikon_ActiveDLighting',
'com.robcole.lightroom.ExifMeta.Nikon_AutoDistortionControl',
'com.robcole.lightroom.ExifMeta.Nikon_Brightness',
'com.robcole.lightroom.ExifMeta.Nikon_Contrast',
'com.robcole.lightroom.ExifMeta.Nikon_FilterEffect',
'com.robcole.lightroom.ExifMeta.Nikon_FlashExposureComp',
'com.robcole.lightroom.ExifMeta.Nikon_FocusDistance',
'com.robcole.lightroom.ExifMeta.Nikon_FocusMode',
'com.robcole.lightroom.ExifMeta.Nikon_HueAdjustment',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlAdjust',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlBase',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlName',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlQuickAdjust',
'com.robcole.lightroom.ExifMeta.Nikon_PictureControlVersion',
'com.robcole.lightroom.ExifMeta.Nikon_Quality',
'com.robcole.lightroom.ExifMeta.Nikon_Saturation',
'com.robcole.lightroom.ExifMeta.Nikon_Sharpness',
'com.robcole.lightroom.ExifMeta.Nikon_ShootingMode',
'com.robcole.lightroom.ExifMeta.Nikon_VibrationReduction',
{ 'com.adobe.label', label = 'Olympus' },
'com.robcole.lightroom.ExifMeta.Olympus_AFPoint',
'com.robcole.lightroom.ExifMeta.Olympus_FlashExposureComp',
'com.robcole.lightroom.ExifMeta.Olympus_FocusDistance',
'com.robcole.lightroom.ExifMeta.Olympus_FocusMode',
'com.robcole.lightroom.ExifMeta.Olympus_MeteringMode',
'com.robcole.lightroom.ExifMeta.Olympus_PictureMode',
'com.robcole.lightroom.ExifMeta.Olympus_SceneMode',
{ 'com.adobe.label', label = 'XMPaux' },
'com.robcole.lightroom.ExifMeta.XMPaux_ApproximateFocusDistance',
{ 'com.adobe.label', label = 'XMPcrs' },
'com.robcole.lightroom.ExifMeta.XMPcrs_WhiteBalance',
{ 'com.adobe.label', label = 'XMPexif' },
'com.robcole.lightroom.ExifMeta.XMPexif_FocalLengthIn35mmFormat',
},
},
}